"""add subcounty to assets

Revision ID: 138c8830c84b
Revises: 7dce381a767a
Create Date: 2026-07-31 08:49:23.268736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '138c8830c84b'
down_revision: Union[str, Sequence[str], None] = '7dce381a767a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('county_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # op.create_index('idx_sub_counties_geometry', 'sub_counties', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_sub_counties_county_id'), 'sub_counties', ['county_id'], unique=False)
    op.create_index(op.f('ix_sub_counties_id'), 'sub_counties', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_counties_id'), table_name='sub_counties')
    op.drop_index(op.f('ix_sub_counties_county_id'), table_name='sub_counties')
    op.drop_index('idx_sub_counties_geometry', table_name='sub_counties', postgresql_using='gist')
    op.drop_table('sub_counties')
    # ### end Alembic commands ###
