"""add core domain models

Revision ID: 3602d63eb89c
Revises: 817587825d0c
Create Date: 2026-07-28 17:37:12.537278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3602d63eb89c'
down_revision: Union[str, Sequence[str], None] = '817587825d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('asset_type', sa.Enum('HOSPITAL', 'SCHOOL', 'SHELTER', 'VILLAGE', 'ROAD', 'BRIDGE', name='assettype'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resource_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.Enum('AMBULANCE', 'BOAT', 'TRUCK', 'HELICOPTER', name='resourcetype'), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'DEPLOYED', 'MAINTENANCE', name='resourcestatus'), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warning_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['warning_id'], ['warnings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warning_id', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('villages', sa.Integer(), nullable=False),
    sa.Column('roads', sa.Integer(), nullable=False),
    sa.Column('hospitals', sa.Integer(), nullable=False),
    sa.Column('schools', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['warning_id'], ['warnings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warning_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['warning_id'], ['warnings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recommendation_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resource_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations')
    op.drop_table('recommendations')
    op.drop_table('impact_analysis')
    op.drop_table('feedback')
    op.drop_table('resource_units')
    op.drop_table('assets')
    # ### end Alembic commands ###
