"""add county and source to assets

Revision ID: 4aea581a2702
Revises: 7501fcc9abab
Create Date: 2026-07-30 09:12:35.918549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aea581a2702'
down_revision: Union[str, Sequence[str], None] = '7501fcc9abab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('county', sa.String(length=100), nullable=False))
    op.add_column('assets', sa.Column('source', sa.String(length=150), nullable=False))
    op.drop_column('assets', 'latitude')
    op.drop_column('assets', 'longitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('assets', 'source')
    op.drop_column('assets', 'county')
    # ### end Alembic commands ###
