"""add county spatial table

Revision ID: 7501fcc9abab
Revises: 3602d63eb89c
Create Date: 2026-07-29 14:55:14.751037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7501fcc9abab'
down_revision: Union[str, Sequence[str], None] = '3602d63eb89c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # op.create_index('idx_counties_geometry', 'counties', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_counties_id'), 'counties', ['id'], unique=False)
    op.add_column('assets', sa.Column('geometry', geoalchemy2.types.Geometry(srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False))
    # op.create_index('idx_assets_geometry', 'assets', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('idx_assets_geometry', table_name='assets', postgresql_using='gist')
    op.drop_column('assets', 'geometry')
    op.drop_index(op.f('ix_counties_id'), table_name='counties')
    # op.drop_index('idx_counties_geometry', table_name='counties', postgresql_using='gist')
    op.drop_table('counties')
    # ### end Alembic commands ###
