"""add subcounty to assets

Revision ID: 7dce381a767a
Revises: d7795e75ce95
Create Date: 2026-07-31 08:36:51.916350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7dce381a767a'
down_revision: Union[str, Sequence[str], None] = 'd7795e75ce95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('subcounty', sa.String(length=100), nullable=True))
    op.drop_constraint(op.f('counties_name_key'), 'counties', type_='unique')
    op.add_column('warnings', sa.Column('subcounty', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('warnings', 'subcounty')
    op.create_unique_constraint(op.f('counties_name_key'), 'counties', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'subcounty')
    # ### end Alembic commands ###
