"""add subcounty relationship to warnings

Revision ID: aadcbea7c3f0
Revises: 138c8830c84b
Create Date: 2026-07-31 12:13:14.374981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aadcbea7c3f0'
down_revision: Union[str, Sequence[str], None] = '138c8830c84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warnings', sa.Column('subcounty_id', sa.Integer(), nullable=True))
    op.alter_column('warnings', 'subcounty',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index(op.f('ix_warnings_subcounty_id'), 'warnings', ['subcounty_id'], unique=False)
    op.create_foreign_key(None, 'warnings', 'sub_counties', ['subcounty_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'warnings', type_='foreignkey')
    op.drop_index(op.f('ix_warnings_subcounty_id'), table_name='warnings')
    op.alter_column('warnings', 'subcounty',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('warnings', 'subcounty_id')
    # ### end Alembic commands ###
