"""made changes to warning model

Revision ID: d7795e75ce95
Revises: 4aea581a2702
Create Date: 2026-07-30 15:15:19.842223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7795e75ce95'
down_revision: Union[str, Sequence[str], None] = '4aea581a2702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impact_analysis', sa.Column('summary', sa.JSON(), nullable=False))
    op.add_column('impact_analysis', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('impact_analysis', 'villages')
    op.drop_column('impact_analysis', 'population')
    op.drop_column('impact_analysis', 'hospitals')
    op.drop_column('impact_analysis', 'roads')
    op.drop_column('impact_analysis', 'schools')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impact_analysis', sa.Column('schools', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('impact_analysis', sa.Column('roads', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('impact_analysis', sa.Column('hospitals', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('impact_analysis', sa.Column('population', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('impact_analysis', sa.Column('villages', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('impact_analysis', 'created_at')
    op.drop_column('impact_analysis', 'summary')
    # ### end Alembic commands ###
